# Generated by Django 5.0.4 on 2024-05-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_alter_employee_overtime_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
